name: Deploy to VPS

on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar proyecto
        run: mvn clean package -DskipTests

      - name: Copiar archivos al VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "target/*.jar,Dockerfile,docker-compose.yml"
          target: "/home/app/test-devops"
          debug: true

      - name: Desplegar en VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/app/test-devops
            docker compose down
            docker compose up -d --build
            docker image prune -f
